// Generated by nitro
import type { Serialize, Simplify } from 'nitropack'
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/header': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/header').default>>>>
    }
    '/api/search-right': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/search-right').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
  }
}
export {}